[project]
name = "learn2slither"
version = "1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alfux-mlp>=1.0.5",
    "bidict>=0.23.1",
    "crossfiledialog>=1.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pyglet>=2.1.13",
    "pyqt6>=6.11.0",
]

[tool.uv.sources]
alfux-mlp = { git = "ssh://git@github.com/alfux/multilayer-perceptron.git" }
